### ISSUE TITLE
Prepare 2.0.0 release

### ISSUE THREAD

**Issue by vadeg** [zalando/zally#1166]
Make Zally 2.0.0 release

### Tasks

- [x] Create release draft on GH
- [x] Publish artefacts to Maven Central
- [ ] Build CLI and add to the release
- [x] Update `README` on how to make releases (see #1168 )
- [x] Add release notes and publish release

**Comment by vadeg** [comment]
Closes #964
