### ISSUE TITLE
Implement Meta Information Rules

### ISSUE THREAD

**Issue by tkrop** [zalando/zally#636]
**Background**: from API management perspective meta information is very important. Currently, APIs often neglect to provide even the most simple information. To address this issue we recently added and improved some meta information rules, that are easy to implement in Zally but should have big impact.

- [ ] [Must: Contain API Meta Information [218]](http://zalando.github.io/restful-api-guidelines/#218)
- [x] [Must: Provide API Audience [219]](http://zalando.github.io/restful-api-guidelines/#219)
- [x] [Should: Provide API Identifiers [215]](http://zalando.github.io/restful-api-guidelines/#215)

**Comment by vadeg** [comment]
I seems that rules 215 and 219 have been implemented already. I have implemented rule 219 (see #703 )
