### ISSUE TITLE
Remove deprecated paths field from Violation

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#858]
The `Violation` class currently allows reporting in either unstructured paths or strongly typed json pointers. Once the transition to `Context` based rules is complete in #834 then there are a few more cases that need addressing to tidy up:

- [x] `AvoidXZallyIgnoreRule` pull request #859 
- [x] `UseProblemJsonRule` pull request #860 
- [x] `ExtractBasePathRule` pull request #861
- [x] `HyphenatedHttpHeadersRule` likely addressed via #834
- [x] `NoUnusedDefinitionsRule` likely addressed via #834
- [ ] `RulesValidator`
- [ ] Remove the fields and unnecessary constructors from `Violation`
